Friends/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.first_app.urls', namespace = 'user')),
    url(r'^', include('apps.second_app.urls', namespace = 'friends')),
]

apps/first_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout'),

]

apps/second_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home$', views.home),
    url(r'^addpage$', views.addpage),
    url(r'^add$', views.add),
    url(r'^show$', views.show),

]

apps/first_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re
# Create your models here.
class UserManager(models.Manager):
    def registerVal(self, postData):
        results = {'status': True, 'errors': []}
        user = []

        if not postData['first_name'] or len(postData['first_name']) < 3:
            results['status'] = False
            results['errors'].append('First name needs to be longer than 2 characters.')

        if not postData['last_name'] or len(postData['last_name']) < 3:
            results['status'] = False
            results['errors'].append('Last name needs to be longer than 2 characters.')

        if not postData['email'] or len(postData['email']) < 5 or not re.match(r"[^@]+@[^@]+\.[^@]+", postData['email']):
            results['status'] = False
            results['errors'].append('Email is invalid')

        if not postData['password'] or len(postData['password']) < 5:
            results['status'] = False
            results['errors'].append('Password needs to be at least 5 characters long.')

        if results['status'] == True:
            user = User.objects.filter(email = postData['email'])

        if len(user) != 0:
            results['status'] = False
            results['errors'].append('User already exists. Please try another email.')

        print results['status']
        print results['errors']
        return results


    def loginVal(self, postData):
        results = {'status':True, 'errors': [], 'user': None}

        if len(postData['email']) < 3:
            results['status'] = False
            results['errors'].append('Something went wrong. Double check everything.')

        else:
            user = User.objects.filter(email = postData['email'])

            if len(user) <= 0:
                results['status'] = False
                results['errors'].append('Something went wrong. Double check everything.')

            elif len(postData['password']) < 5 or postData['password'] != user[0].password:
                results['status'] = False
                results['errors'].append('Something went wrong. Double chekc everything.')

            else:
                results['user'] = user[0]

        print results['status']
        print results['errors']
        return results

    def createUser(self, postData):
        p_hash = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
        user = User.objects. create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], password = postData['password'])
        return user


class User(models.Model):
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    password = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

apps/second_app/models.py
from __future__ import unicode_literals

from django.db import models

from ..first_app.models import User
# Create your models here.
class FriendManager(models.Manager):
    def MakeFriend(self, postData):
        friend = User.objects.create(first_name = postData['first_name'], last_name = postData['last_name'])
        return friend


class Friend(models.Model):
    first_name = models.CharField(max_length = 100, null = True)
    last_name = models.CharField(max_length = 100)
    user = models.ForeignKey(User, null = True, default = 1)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = FriendManager()

apps/first_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

print User
# Create your views here.
def index(request):
    print '*** index ***'
    return render(request, 'first_app/index.html')

def register(request):
    print '*** register ***'
    results = User.objects.registerVal(request.POST)
    if results['status'] == False:
        for error in results['errors']:
            messages.error(request, error)
    else:
        user = User.objects.createUser(request.POST)
        messages.success(request, 'User has been created!')

    return redirect('/')

def login(request):
    print '*** login ***'
    results = User.objects.loginVal(request.POST)
    if results['status'] == False:
        for error in results['errors']:
            messages.error(request, error)
        return redirect('/')
    else:
        request.session['first_name'] = results['user'].first_name
        request.session['user_id'] = results['user'].id
        return redirect('/home')


def logout(request):
    print '*** logout ***'
    request.session['user_id']=None
    return redirect('/')

apps/second_app/views.py
from django.shortcuts import render, redirect
from ..first_app.models import User
from .models import Friend
from django.contrib import messages


# Create your views here.
def home(request):
    print '*** home ***'
    if not request.session['user_id']:
        return redirect('/')
    context = {
        'friends' : Friend.objects.all().order_by('-created_at')[3:],
        'users' : User.objects.all()
    }
    return render(request, 'second_app/home.html', context)

def addpage(request):
    if not request.session['user_id']:
        return redirect('/')
    return render(request, 'second_app/add.html')

def add(request):
    print '*** add ***'
    if not request.session['user_id']:
        return redirect('/')
    friend = Friend.objects.create(first_name = request.POST['first_name'])
    return render(request, 'second_app/add.html')

def show(request):
    print '*** show ***'
    if not request.session['user_id']:
        return redirect('/')
    return render(request, 'second_app/friends.html')

apps/first_app/templates/first_app/index.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<title>Login and Registration</title>
	</head>
	<body>
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'error' %}
					<p style="color: red">{{message}}</p>
				{%endif%}
				{% if message.tags == 'success' %}
					<p style="color: green">{{message}}</p>
				{%endif%}
			{%endfor%}
		{%endif%}

		<h1>Login:</h1>
		<form action="/login" method="post">
		{% csrf_token %}
			<label>Email:</label>
			<input type="text" name="email">
			<br><br>
			<label>Password:</label>
			<input type="password" name="password">
			<br><br>
			<input type="submit" value="Login">
		</form>
		<br><br>
		<h1>Register:</h1>
		<form action="/register" method="post">
		{% csrf_token %}
			<label>First Name:</label>
			<input type="text" name="first_name">
			<br><br>
			<label>Last Name:</label>
			<input type="text" name="last_name">
			<br><br>
			<label>Email:</label>
			<input type="text" name="email">
			<br><br>
			<label>Password:</label>
			<input type="password" name="password">
			<br><br>
			<label>Confirm Password:</label>
			<input type="password" name="con_password">
			<br><br>
			<input type="submit" value="Register">
		</form>
	</body>
</html>

apps/second_app/templates/second_app/add.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="utf-8">
		<title>Add Friends</title>
	</head>
	<body>
		<header>
			<h1>Pick A Friend to Add</h1>
		</header>
		<form action="/addfriend" method="post">
		<table>
			<tr>
				<th>Name</th>
				<th>Status</th>
				<th>Time</th>
			</tr>
			{%for user in users %}
				<tr>
					<td>{{user.first_name}}{{user.last_name}}</td>
					<td><input type="hidden" name="first_name" value="{{user.first_name}}"></td>
					<td><input type="hidden" name="last_name" value="{{user.last_name}}"></td>
					<td><input type="submit" value="Add as Friend"></td>
				</tr>
			{%endfor%}
		</table>
		</form>
	</body>
</html>

apps/second_app/templates/second_app/friends.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Show: Friends</title>
	</head>
	<body>
		<form action="/show" method="post">
			<h1>Friends:</h1>
			<a href="{%url 'friends:home'%}">Go Back Home</a>
			{%for friend in friends%}
				{%if friend.id == request.session.user_id%}
					<p>{{friend.first_name}}</p>
				{%endif%}
			{%endfor%}
		</form>
	</body>
</html>

apps/second_app/templates/second_app/home.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Homepage</title>
	</head>
	<body>
		<header>
			<h1>Welcome, {{request.session.first_name}}</h1>
			<table style="float: right;">
				<tbody>
					<td><a href="{%url 'user:logout'%}">Logout</a></td>
				</tbody>
			</table>
		</header>
		<br><br><br>
		<table>
			<tbody>
				<td><a href="/show">View Friends</a></td>
				<td><a href="/addpage">Add Friends</a></td>
			</tbody>
		</table>
		<h2>Recent Friends</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Status</th>
					<th>Time</th>
				</tr>
				{%for user in users %}
					<tr>
						<td>{{user.first_name}}</td>
						<td>Added</td>
						<td>{{user.created_at}}</td>
					</tr>
				{%endfor%}
			</table>
	</body>
</html>